### ISSUE TITLE
ocide: issues with build property window

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#105]
1. this window currently has no icon
2. this window currently cannot be closed with [ESC]
3. as long as this window is open I cannot switch back to OCIDE with [ALT]+[TAB]
4. this window is currently not modal (which may also the reason for 3) - as there is no option to switch to another file's (or project's) property (the property part is deactivated in context menu) I don't think this is useful
5. when opening the properties of a single file the property window is empty:

![grafik](https://user-images.githubusercontent.com/6699539/39709438-1b26df24-521a-11e8-9b1e-7c602aad9154.png)

the project's properties are shown when a click is done on "Compiler Settings" (I assumed they are inherited until changed):
![grafik](https://user-images.githubusercontent.com/6699539/39709497-5154a446-521a-11e8-870e-7742e7771123.png)

I think it is reasonable to always show the first property group - especially if there is only one like in the source file case.

**Comment by LADSoft** [comment]
this should be fixed.

**Comment by LADSoft** [comment]
were you going to recheck this?

**Comment by GitMensch** [comment]
Yes. 1-3+5 are fixed.
The fix for 3 (completely separate window)and the suggestion for 4 (modal window) conflict, which is OK we can drop 4 if you want it this way, but in this case it should be possible to re-open the property window (currently disabled when open).

And as shown in the other issue:

The display is strange now - the first "panel" seems to be missing, I've seen it before but it is gone since some versions (or in CI builds in general)?

![grafik](https://user-images.githubusercontent.com/6699539/40589677-0a8e2b76-61f2-11e8-8f27-6255e18a6972.png)

**Comment by GitMensch** [comment]
The top part is better now (still not enough space) but the button part has no space any more:

![grafik](https://user-images.githubusercontent.com/6699539/40659382-6383fdc0-634e-11e8-8c39-8e4193a86dc8.png)

The option to change the property even when property window is already open works now (for changed values there's also the needed popup what to do) - only the size issue is currently open.
Note: I *guess* there may be hi-dpi issues, too (but I have no environment to check).
