### ISSUE TITLE
[wish] "/c file.cpp /o..\objs\" as "/c file.cpp /o..\objs\file.o"

### ISSUE THREAD

**Issue by lionfaith** [LADSoft/OrangeC#26]
Hi!
When wanting to compile from one directory to another, occ forces the user to state the whole target like so: ```occ /c file.cpp /o..\objs\file.o```. When trying to omit the target name, it creates a file with no name, that is ```occ /c file.cpp /o..\objs\``` will create a ```..\objs\.o``` file.

My wish is that ```occ /c file.cpp /o..\objs\``` be automatically interpreted as ```occ /c file.cpp /o..\objs\file.o```.

Thank in advance for your attention,
Lionfaith

**Comment by LADSoft** [comment]
Hi lionfaith,

note the way this is normally handled is with a make file...

But this sounded like a good thing to help with simple projects so I 
implemented it for you.   My implementation is a little looser than you 
asked for below, for example:

occ /c file1.cpp file2.cpp file3.cpp /o..\objs\

puts ALL the object files in the ..\objs directory.

likewise if you omit the /c to make an EXE it will stick the exe in the 
output directory as well.

This relies on the directory name having a trailing '\' - without the 
trailing '\' it will assume it is not a directory but a file and work 
the same way as it did before.

It is in the 6.02 release I just put on my web site.


David

lionfaith wrote:

**Comment by lionfaith** [comment]
Hi David,
your addition is working, thanks!

I'm effectively gently avoiding use of makefiles. I never liked it.

I thought using omake at some point but I step on a problem and didn't know how to solve because omake is still undocumented. Would you mind if I report it here?

I tried omake on a gnu makefile. It wasn't supposed to work because everything is configured for a unix system.  I gave it a try anyway and omake made strange complains about each .o file this way `Error makefile(37): No rule to make target 'ai.o'`, line 37 being the last one of the file. The standard rules of the makefile are (I'm not reporting here the phony targets):
```makefile
# top-level rule to create the program.
all: $(PROG)

# compiling other source files.
%.o: code/%.cpp code/%.h code/structs.h code/defs.h code/classes.h
	$(CXX) $(CFLAGS) -c -O3 -DVERSION=\"$(VERSION)\" -DPACKLOCATION=\"$(DATADIR)$(PACK)\" $<

# linking the program.
$(PROG): $(OBJS)
	$(CXX) $(LIBS) $(OBJS) -o $(PROG)
```

I hope it helps.
Thank for your job!
Lionfaith

**Comment by LADSoft** [comment]
Hi Lionfaith,

I'm so glad you appreciate my work!

The problem with makefiles is you have to take time to create them 
lol!   For small projects or for testing it isn't always worth it.   
That is why I add additions like the one you suggested....

I don't know if you are aware but after your addition and one other 
addition I made last year you can now do something like:

occ code\*.cpp /ooutput\

to compile all source files from the code directory and put the output 
files in the output directory.   But the problem is you don't get 
control over the exe file name if you do that :(.

That kind of simple command line is perfect for small to medium projects 
that don't require a lot of custom build configuration, and it is great 
when you are doing one-offs or prototyping and don't want to spend a lot 
of time concentrating on how to build your project.

omake is supposed to be GNU make compatible but it is hard since I've 
never actually used GNU make.   But it comes close...   I don't actually 
know if anyone uses it or would use it if it was more compatible, since 
it is easy to plug in a more highly vetted make program...   but it was 
a fun program to write :)

There are a couple of bugs in omake apparently...   it doesn't like the 
%.o line in the example you gave because of the constant file names.   
Also once you get past that the compiler can't find the .o files to do 
the link....   I'm not sure offhand what the resolution for that will 
be.   I think though that omake isn't stripping the path properly (it is 
putting the output files in the code/ directory).   I will look into it 
in a few days...

Thanks for reporting it!

David


lionfaith wrote:

**Comment by lionfaith** [comment]
Glad to make you glad! :)

I've just tested `occ /c code\*.cpp /ooutput\` (without the `/c` it won't link), it works well! The output is clearer, and errors still output nicely. Would you mind mention this trick in the documentation for fear that this precious knowledge is reserved for initiates only?

Still about `occ /c code\*.cpp /ooutput\`, how does it go about memory consumption? Is it reset at each file compilation like it would if compilation were done explicitly separately?

For about the makefile excerpt I gave you, I omitted the definition of the variables. It might help you to know to know that `OBJS` is explicitly defined this way:
```
OBJS = ai.o aliens.o audio.o bullets.o cargo.o collectable.o comms.o debris.o events.o explosions.o game.o globals.o graphics.o init.o intermission.o loadSave.o messages.o misc.o missions.o player.o resources.o script.o shop.o Starfighter.o title.o unpack.o weapons.o
```

Lionfaith

**Comment by LADSoft** [comment]
Hi Lionfaith,

I am updating the documentation :)

As far as the memory consumption goes, OCC allocates memory out of 
blocks in an internal memory pool.   At the end of compiling each file 
all the blocks are returned to a free list and reused for the next file.

Yeah I actually wrote a small make file with the excerpt you gave me 
then added a line similar to your OBJS line below as that is a common 
thing to do in make files.   That is how I was able to comment on bugs :)

David

lionfaith wrote:

**Comment by lionfaith** [comment]
This is cool. With such a memory allocation strategy, it really means that `occ /c code\*.cpp /ooutput\` is equivalent to a series of `occ /c code\$(src).cpp /ooutput\`. Well, actually, `occ /c code\*.cpp /ooutput\` is better and a lot nicer.

For the $objs variable, I talked about it just to be sure.

Lionfaith

**Comment by LADSoft** [comment]
It is a little harder on me though as I can't just globally initialize 
compiler variables at file scope, I have to explicitly initialize every 
global variable in an initialization function then be sure to call that 
function before the compile starts...   I've been known to mess that 
process up sigh.   I guess I should make that one of the things I 
explicitly test prior to each release, well that is a good idea I'll go 
convert one of my test projects :)

lionfaith wrote:

**Comment by LADSoft** [comment]
Hi lionfaith,

the main problem with that small make excerpt you gave me was that it 
was using '/' as a directory separator...    omake needs '\'. There was 
also a problem with the -o switch in the compile line; occ doesn't like 
a space there.   Beyond that there was one problem with omake where it 
was considering the '\' as a quote character in one instance where it 
should have considered it a directory separator; I've fixed that and put 
up version 6.0.3.

I think maybe omake should allow '/' for directory separators but that 
was a bigger job than I wanted to tackle right now; I will keep it in 
mind for the future though.

The other main problem with omake is that it is case sensitive BUT the 
windows file system is not...   that has bitten me sometimes.

Here is my update to the small excerpt of a make file you had for reference:

PROG=hi.exe
OBJS = a1.o b1.o

# top-level rule to create the program.
all: $(PROG)

# compiling other source files.
%.o: code\%.c code\%.h  code\structs.h code\defs.h code\classes.h
     occ -c $<

# linking the program.
$(PROG): $(OBJS)
     occ $(OBJS) -o$(PROG)


this will work with version 6.0.3 of the compiler package.

Thanks,

David

lionfaith wrote:

**Comment by lionfaith** [comment]
Hi David,
unfortunately, this is not working all too well for now. Here is my makefile:
```makefile
LIBS = extern\occlib\SDLmain.l extern\occlib\SDL.l extern\occlib\SDL_mixer.l extern\occlib\SDL_image.l
OBJS = target\objs\ai.o target\objs\aliens.o target\objs\audio.o target\objs\bullets.o target\objs\cargo.o target\objs\collectable.o target\objs\comms.o target\objs\debris.o target\objs\events.o target\objs\explosions.o target\objs\game.o target\objs\globals.o target\objs\graphics.o target\objs\init.o target\objs\intermission.o target\objs\loadSave.o target\objs\messages.o target\objs\misc.o target\objs\missions.o target\objs\player.o target\objs\resources.o target\objs\script.o target\objs\shop.o target\objs\Starfighter.o target\objs\title.o target\objs\unpack.o target\objs\weapons.o

# top-level rule to create the program.
all: starfighter.exe

# compiling other source files.
%.o: src\%.cpp src\%.h src\structs.h src\defs.h src\classes.h
	occ /c $< /otarget\objs\

# linking the program.
starfighter.exe: $(OBJS) $(LIBS)
	occ $(LIBS) $(OBJS) /otarget\starfighter.exe
	copy target\starfighter.exe app\

# cleaning everything that can be automatically recreated with "make".
clean:
	del target\objs\*.o
	del app\starfighter.exe
	del target\starfighter.exe
```
And I got this error:
```
Error makefile(20): Command line too long:
occ extern\occlib\SDLmain.l extern\occlib\SDL.l extern\occlib\SDL_mixer.l extern\occlib\SDL_image.l target\objs\ai.o target\objs\aliens.o target\objs\audio.o target\objs\bullets.o target\objs\cargo.o target\objs\collectable.o target\objs\comms.o target\objs\debris.o target\objs\events.o target\objs\explosions.o target\objs\game.o target\objs\globals.o target\objs\graphics.o target\objs\init.o target\objs\intermission.o target\objs\loadSave.o target\objs\messages.o target\objs\misc.o target\objs\missions.o target\objs\player.o target\objs\resources.o target\objs\script.o target\objs\shop.o target\objs\Starfighter.o target\objs\title.o target\objs\unpack.o target\objs\weapons.o /otarget\starfighter.exe

Error makefile(20): commands returned error code 255
```

I made another version which got the pathes wrong but which at least did not the overlong command line, but I had this error:
```
        occ /c src\ai.cpp /otarget\objs\# linking the program.
occ Version 6.0.3.1 Copyright (C) LADSoft 2006-2016

Fatal error: Cannot specify output file for multiple input files

Error makefile(20): commands returned error code 1
```

It is like the double return between `/otarget\objs\` and `# linking the program.` got escaped. And the command line doesn't like it.

I hope it helps.

Lionfaith

**Comment by LADSoft** [comment]
Hi lionfaith,

usually I personally put my list of object files in a temporary file to 
keep it from overflowing the command line, however, I checked and 
windows allows a much longer command line than omake did:
omake limited it to 500 characters whereas the windows limitation is 
around 8190.   So I upped the limit in the 6.04 release I just put up, 
*however* don't know if that will work for your particular case.

you can also use 'vpath' to specify directories to make the command 
lines shorter.

If you want to try to use a temporary file here is an example out of one 
of the orange C make files:

     $(LINK) /o$(NAME).exe $(TYPE) $(LFLAGS) @&&|
$(STARTUP) $(addprefix $(_OUTPUTDIR)\,$(MAIN_DEPENDENCIES))
$(_LIBDIR)\$(NAME)$(LIB_EXT) $(LIB_DEPENDENCIES) $(COMPLIB)
$(DEF_DEPENDENCIES)
$(addprefix $(_OUTPUTDIR)\,$(RES_deps))
|

This is an olink command.  Here the important parts are the @&&|, which 
starts a temporary file with a contents delimiter of '|'...   and the 
contents delimiter of '|' a few lines later.   Everything in between 
gets put in the temporary file after expansion of macros and so forth.

The tools all handle these kinds of temporary files...

the other problem you had is the line

|occ /c src\ai.cpp /otarget\objs\# linking the program. |

as written that is wrong because the '#' here is not interpreted by 
omake and would be passed on to the OS, e.g. it would be part of a file 
name for this command.   But, I just reread what you wrote and it seems 
you may have intended to have a couple of blank lines here?   While this 
works in general I looked at the code and it *may* have trouble with 
unix-style line endings here.   In this particular context omake 
requires '\r' characters.   IF you can confirm that you did have a 
couple of blank lines here I will revisit this again.

David

lionfaith wrote:

**Comment by lionfaith** [comment]
The update to make omake accept longer line works fine for me!

`vpath`? What is it? It is nowhere in the doc... Ok, I googled it: it's in the doc of gnu make. And omake can do this too, good to know.

`@&&|...|` is an interesting feature. I didn't know it.

About the line `occ /c src\ai.cpp /otarget\objs\# linking the program. `, I wasn't clear enough, sorry, my fault. It did effectively come from
```makefile
%.o: src\%.cpp src\%.h src\structs.h src\defs.h src\classes.h
	occ /c $< /otarget\objs\

# linking the program.
```
The line endings were set to `LF`. I tested with `CRLF`, it gives the same error.

I hope all this helps you,
Lionfaith

**Comment by LADSoft** [comment]
Hi lionfaith,

glad the command line length update works!

It took me a while to see the problem with the comment.   Turns out my 
familiarity with omake bit me as I had just automatically adjusted for 
it when I typed in the examples you gave a few days ago...

the problem is that in GNU make '\' at the end of a line is a line 
continuator, the same as in C.    But since it is also a path separator 
in omake (which is not a problem in GNU make) and you placed it at the 
end of a line there is some ambiguity as to what it should mean in that 
context.

an immediate fix is just to put one or more spaces at the end of the 
line, so that the continuator does not come last.   I will find out why 
it is concatenating multiple lines though...   it should have stopped 
after concatenating the single blank line after the command list.

Thanks!

David
lionfaith wrote:

**Comment by LADSoft** [comment]
Hi lionfaith,

I didn't resolve the ambiguity with '\', but I did fix it so that it 
won't concatenate multiple lines...  version 6.05 is on my web site.

David

lionfaith wrote:

**Comment by lionfaith** [comment]
Hi David,
it works now, thanks!

But while testing, I hit a strange behavior of occ which was messing the behavior of omake. I simply forgot the include switch `\I` for the command, I then obviously got errors about missing "SDL\SDL.h" and about missing types, one part of errors, one part of warnings, all with the first file coming from the rules: ai.cpp. I corrected the makefile, rerun omake and then got errors at linking:
```
Error: Invalid object file in line 1 in target\objs\ai.o
Error: Undefined External setEnemyAI(object*) in module C:\usr\dev\starfighter\lion-0.1\src\aliens.cpp
Error: Undefined External setKlineAI(object*) in module C:\usr\dev\starfighter\lion-0.1\src\aliens.cpp
Error: Undefined External setKlineAttackMethod(object*) in module C:\usr\dev\starfighter\lion-0.1\src\bullets.cpp
```
After invertigation, I realised that during this rerun ai.o wasn't rebuilt. This is because of the first error I made. Although the compilation of ai.o was legitimately giving errors, occ produced an object file anyway.

So, to put it simply:
```
C:\usr\dev\starfighter\lion-0.1>omake clean
        del target\objs\*.o
        del app\starfighter.exe
        del target\starfighter.exe
C:\usr\dev\starfighter\lion-0.1>occ /c src\ai.cpp /otarget\objs\
occ Version 6.0.5.1 Copyright (C) LADSoft 2006-2016

Error    C:\usr\dev\starfighter\lion-0.1\src\ai.h(25):  Cannot open include file "SDL/SDL.h"
Error    C:\usr\dev\starfighter\lion-0.1\src\ai.h(26):  Cannot open include file "SDL/SDL_image.h"
Error    C:\usr\dev\starfighter\lion-0.1\src\ai.h(27):  Cannot open include file "SDL/SDL_mixer.h"
Warning  C:\usr\dev\starfighter\lion-0.1\src\structs.h(48):  Missing type in declaration
Error    C:\usr\dev\starfighter\lion-0.1\src\structs.h(48):  Syntax error: ; expected
[similar pairs of warning and error omited]
Warning  C:\usr\dev\starfighter\lion-0.1\src\classes.h(171):  Missing type in declaration
Error    C:\usr\dev\starfighter\lion-0.1\src\classes.h(171):  Syntax error: ; expected
[similar pairs of warning and error omited]
26 Errors
C:\usr\dev\starfighter\lion-0.1>cd target\objs

C:\usr\dev\starfighter\lion-0.1\target\objs>dir
[some informations omited]
 Répertoire de C:\usr\dev\starfighter\lion-0.1\target\objs

18-08-16  03:10                 0 ai.o
```
As you can read, `ai.o` is a totally empty file of 0ko. I suppose this is not an expected behavior, so I reported it here.

This issue 26 is already a long one, Might we keep courage, we're going to see an end to it. And I also hope this report shall help you.

Lionfaith

**Comment by LADSoft** [comment]
Hi Lionfaith!

yes that is a bug.   The compiler most defintitely should not produce 
output when there are errors.

It is relatively recent, I think I inadvertantently introduced it while 
adding the directory option for the /o switch sigh.   I'm glad you 
caught it!

I have put up a new version 6.07 which should fix it.

David

lionfaith wrote:

**Comment by lionfaith** [comment]
It seems to work well. When doing `omake clean` then `occ /c src\ai.cpp /otarget\objs\`, it doesn't produce `target\objs\ai.o`.

But actually it doesn't work entirely correctly yet: if instead I first do `omake` then do `occ /c src\ai.cpp /otarget\objs\`, it deletes the  `target\objs\ai.o` omake generated.

Lionfaith

**Comment by LADSoft** [comment]
Hi lionfaith,

that is actually by design, because when making an assembly language 
file the file is sent to disk piecemeal during the compile instead of 
all at once at the end.   I'm thinking though about whether to change
the design at least for .o files since the behavior you describe below 
is somewhat nicer.   Will get back to you :)

David

lionfaith wrote:

**Comment by LADSoft** [comment]
Hi lionfaith,

I'm sorry about the delay; lycos was down over the weekend due to a 
cyber-attack so I couldn't put the files up for release.

I've put up a new version 6.0.8 which has the following behavior:

1) if the compile succeeds a new output file will be created
2) if the compile fails and an output file had already existed, it will 
still exist
3) if the compile fails and no output file previously existed, there 
will still not be an output file

Thanks,

David

lionfaith wrote:

**Comment by lionfaith** [comment]
Hello David,
I checked all three cases, everything works fine.

Even with this kind of delay, you're still fast. Nice work, really!
Now, I can finally close this issue.

Lionfaith
