### ISSUE TITLE
Compiling PE for older versions of Windows (IsDebuggerPresent)

### ISSUE THREAD

**Issue by Tom-III** [LADSoft/OrangeC#86]
In a compiled PE file such as
```
int main()
{
    return 0;
}
```
the function IsDebuggerPresent() is somehow added to the import table even though it is never called from my program or the Static CRT initialization.
I did a CTRL+F in the clibs folder and found IsDebuggerPresent to be in clibs/platform/win32/wininc/commonfu.h and clibs/platform/win32/wininc/win32/commonfu.h and clibs/platform/win32/kernel32.def
And nowhere in any initialization code which makes me wonder how it gets added to the import table.  If you open an EXE compiled with OrangeC in Dependency Walker you will see the function indicator lights up.
This function not available in Windows 95 / NT 3.1 / 3.5 which means EXE files that otherwise do not use functions not available in these OSes fail to load.

**Comment by LADSoft** [comment]
hi - I went and looked and the IsDebuggerPresent thing seems to be on the compiler and tools, but not on generated code.   The reason for it is that the compiler as released is compiled with the latest version of the Microsoft toolset, which seems to add this.   The Orange C tool chain does not add it however.

That said, there was nonetheless a problem with the programs the compiler generated.   It used subsystem 5.1 on the executables, which I think would prevent programs from running on windows versions before XP..   I've changed that back to 4.0...   if you want to snag the current test build from the appveyor artifacts page you can test it.  (See readme.md for a link).

The version on the appveyor page is also compiled with itself, which means the compiler should also run on older versions of windows.   But the IDE uses later features and I don't think it will run on anything below windows 7...

**Comment by Tom-III** [comment]
The problem is not with the IDE but with the programs compiled with the orangec compiler

**Comment by LADSoft** [comment]
sorry for the confusion...   I really can find no way for the tools to put IsDebuggerPresent in the executables although it is in the tools themselves for other reasons.   I've done various tests and don't see it...   but there was an unrelated problem that would make compiled executables not work on versions of windows prior to XP.   I fixed that in the repository.   I'm almost ready for the next release, will update this when I get there...   as far as subsystem I've been thinking of exposing the subsystem version numbers...   but the subsystem (e.g. console or windowing) as well as whether it is generating a DLL can be selected with the OLINK /T switch or the occ /W switch.   Is that what you were looking for?

**Comment by Tom-III** [comment]
Yes that would be great, also the minimum version for subsystem is Major 3 Minor A (hex for 3 10) that would be more sensible that 4.0 as it completely removes "artificial" incompatibility.  The program will still fail if you use functions not present in that OS but otherwise it will work.

**Comment by LADSoft** [comment]
I fixed it so you can independently set the versions.   Normally it will figure out the subsystem value on its own but you can override that too now if you want :).   Hint, use linker /D switch to define link-time variables (refer to docs)

**Comment by LADSoft** [comment]
I released V6.0.37.1 today.   Please give feedback as to whether your issues are fixed...
